# Generated by Django 2.2.4 on 2019-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
